### ISSUE TITLE
Some next steps

### ISSUE THREAD

**Issue by cboettig** [eco4cast/neon4cast-catalog#3]
- [x] all `.json` catalog entries should be converted into `.R` versions that generate  (and validate) them.  (see example `catalog.R`) 
- [x] base URLs of all `href` values in links section need to be mapped to use `https://github.com/eco4cast/neon4cast-catalog/raw/main/stac/` instead of `https://projects.ecoforecast.org/neon4cast-catalog/stac` path.  Note: it would probably be good to do this in the R code so that the base URL is set as a variable once and re-used, rather than having the base URL always repeated.
- [x] Any links to asset parquet should adopt the `s3://` notation shown in https://github.com/eco4cast/neon4cast-catalog/blob/2df82596d91c93e02036de6aea5438b1734b4b50/stac/aquatics/models/models.R#L50-L53

- [x] Flush out collection JSON files with descriptions, metadata on tables, etc

- [x] create `scores.R` / `scores.json` stac item JSON (similar to models template like `cb_prophet.json`), with asset element pointing to `s3://` scores notation

## Example directory layout 

```
stac
├── aquatics
│   ├── forecasts
│   │   ├── aquatics.json
│   │   └── models
│   │       ├── asset-description.Rmd
│   │       ├── cb_prophet.json
│   │       └── models.R
│   └── scores
│       ├── scores.json
│       └── scores.R
├── beetles
│   └── beetles.json
├── catalog.json
├── catalog.R
├── noaa
│   └── noaa.json
├── phenology
│   └── phenology.json
└── terrestrial
    └── terrestrial.json
```

**Comment by rqthomas** [comment]
I think we want `https://raw.githubusercontent.com/eco4cast/neon4cast-catalog/main/stac/catalog.json` as the raw GitHub address.

**Comment by cboettig** [comment]
I think we're all good here so I'll close.
